import type { AgentDecision } from '../types';
const ARRAY_FIELDS=['toolCalls','taskChanges','scheduleChanges','memoryCandidates'] as const;
const TASK_STATUSES=['inbox','planned','doing','waiting','done','cancelled'];
const PRIORITIES=['low','normal','high','urgent'];
const JOB_TYPES=['reminder','agent_run','daily_brief','weekly_review'];
const RECURRENCES=['daily','weekly'];
function record(value:unknown,label:string){if(!value||typeof value!=='object'||Array.isArray(value))throw new Error(`${label} must be an object`);return value as Record<string,unknown>}
function text(value:unknown,label:string,max=500){if(typeof value!=='string'||!value.trim())throw new Error(`${label} must be a non-empty string`);if(value.length>max)throw new Error(`${label} is too long`);return value}
function optionalEnum(value:unknown,values:string[],label:string){if(value!==undefined&&!values.includes(String(value)))throw new Error(`Invalid ${label}`)}
function optionalDate(value:unknown,label:string){if(value!==undefined&&(typeof value!=='string'||!Number.isFinite(Date.parse(value))))throw new Error(`Invalid ${label}`)}
export function parseDecision(textValue:string):AgentDecision {
  const cleaned=textValue.replace(/^```(?:json)?\s*|\s*```$/g,'');
  const d=record(JSON.parse(cleaned),'Gemini decision');
  for(const field of ARRAY_FIELDS){if(d[field]===undefined)d[field]=[];if(!Array.isArray(d[field]))throw new Error(`Gemini decision ${field} must be an array`)}
  if(d.response!==undefined){if(typeof d.response!=='string')throw new Error('Gemini decision response must be a string');if(d.response.length>8000)throw new Error('Gemini decision response is too long')}
  const toolCalls=d.toolCalls as unknown[];if(toolCalls.length>6)throw new Error('Too many tool calls');toolCalls.forEach((value,i)=>{const call=record(value,`toolCalls[${i}]`);text(call.id,`toolCalls[${i}].id`,100);text(call.name,`toolCalls[${i}].name`,100);record(call.input,`toolCalls[${i}].input`) });
  const taskChanges=d.taskChanges as unknown[];if(taskChanges.length>10)throw new Error('Too many task changes');taskChanges.forEach((value,i)=>{const change=record(value,`taskChanges[${i}]`);if(!['create','update'].includes(String(change.action)))throw new Error('Invalid task change action');const task=record(change.task,`taskChanges[${i}].task`);if(change.action==='create')text(task.title,`taskChanges[${i}].task.title`,500);else text(task.id,`taskChanges[${i}].task.id`,100);if(task.title!==undefined)text(task.title,`taskChanges[${i}].task.title`,500);optionalEnum(task.status,TASK_STATUSES,'task status');optionalEnum(task.priority,PRIORITIES,'task priority');optionalDate(task.dueAt,'task dueAt')});
  const scheduleChanges=d.scheduleChanges as unknown[];if(scheduleChanges.length>10)throw new Error('Too many schedule changes');scheduleChanges.forEach((value,i)=>{const change=record(value,`scheduleChanges[${i}]`);if(!['create','pause'].includes(String(change.action)))throw new Error('Invalid schedule change action');const job=record(change.job,`scheduleChanges[${i}].job`);if(change.action==='pause')text(job.id,`scheduleChanges[${i}].job.id`,100);else{optionalEnum(job.type,JOB_TYPES,'job type');optionalDate(job.runAt,'job runAt');if(!job.runAt)throw new Error('Scheduled job runAt is required');optionalEnum(job.recurrence,RECURRENCES,'job recurrence');record(job.payload??{},`scheduleChanges[${i}].job.payload`)}});
  const memories=d.memoryCandidates as unknown[];if(memories.length>10)throw new Error('Too many memory candidates');memories.forEach((value,i)=>{const memory=record(value,`memoryCandidates[${i}]`);text(memory.key,`memoryCandidates[${i}].key`,100);text(memory.value,`memoryCandidates[${i}].value`,1000);if(!['personal','project'].includes(String(memory.scope)))throw new Error('Invalid memory scope')});
  return d as unknown as AgentDecision;
}
function generate(prompt:string,json:boolean){ const p=PropertiesService.getScriptProperties(),key=p.getProperty('GEMINI_API_KEY'),model=p.getProperty('GEMINI_MODEL')||'gemini-2.5-flash'; if(!key)throw new Error('Missing GEMINI_API_KEY'); const url=`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${encodeURIComponent(key)}`; const payload:any={contents:[{role:'user',parts:[{text:prompt}]}]};if(json)payload.generationConfig={responseMimeType:'application/json'};const res=UrlFetchApp.fetch(url,{method:'post',contentType:'application/json',muteHttpExceptions:true,payload:JSON.stringify(payload)}); if(res.getResponseCode()>=300)throw new Error(`Gemini request failed: ${res.getResponseCode()}`); const body=JSON.parse(res.getContentText()); return String(body.candidates?.[0]?.content?.parts?.[0]?.text??''); }
export function callGemini(prompt:string):AgentDecision { return parseDecision(generate(prompt,true)||'{}'); }
export function callGeminiReply(prompt:string){return generate(prompt,false).trim()}
