import type { AgentContext, AgentTool } from '../types';

const required=(input:unknown,fields:string[])=>{if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('Input must be an object');const o=input as Record<string,unknown>;fields.forEach(f=>{if(o[f]===undefined||o[f]==='')throw new Error(`Missing ${f}`)});return o};
const stringField=(o:Record<string,unknown>,field:string,max=1000)=>{const value=o[field];if(typeof value!=='string'||!value.trim())throw new Error(`Invalid ${field}`);if(value.length>max)throw new Error(`${field} is too long`);return value.trim()};
const optionalString=(o:Record<string,unknown>,field:string,max=1000)=>{if(o[field]!==undefined)stringField(o,field,max)};
const dateField=(o:Record<string,unknown>,field:string)=>{const value=stringField(o,field,50);if(!Number.isFinite(Date.parse(value)))throw new Error(`Invalid ${field}`);return new Date(value)};
const period=(input:unknown)=>{const o=required(input,['start','end']),start=dateField(o,'start'),end=dateField(o,'end');if(end<=start)throw new Error('end must be after start');if(end.getTime()-start.getTime()>366*86400000)throw new Error('Date range is too large');return o};
const googleId=(o:Record<string,unknown>,field:string)=>{const value=stringField(o,field,200);if(!/^[A-Za-z0-9_-]+$/.test(value))throw new Error(`Invalid ${field}`);return value};

const tools:AgentTool[]=[
 {name:'gmail.search',description:'Search Gmail threads and return metadata',risk:'read',validate:i=>{const o=required(i,['query']);stringField(o,'query',500);return o},execute:i=>GmailApp.search(String(i.query),0,10).map(t=>({threadId:t.getId(),subject:t.getFirstMessageSubject(),lastDate:t.getLastMessageDate().toISOString(),messageCount:t.getMessageCount()}))},
 {name:'gmail.readThread',description:'Read a Gmail thread for summarization and follow-up',risk:'read',validate:i=>{const o=required(i,['threadId']);stringField(o,'threadId',200);return o},execute:i=>{const thread=GmailApp.getThreadById(String(i.threadId));if(!thread)throw new Error('Thread not found');return thread.getMessages().slice(-10).map(m=>({messageId:m.getId(),from:m.getFrom(),to:m.getTo(),date:m.getDate().toISOString(),subject:m.getSubject(),plainBody:m.getPlainBody().slice(0,3000)}))}},
 {name:'gmail.createDraft',description:'Create an email draft',risk:'draft',validate:i=>{const o=required(i,['to','subject','body']),recipients=stringField(o,'to',500).split(',').map(v=>v.trim());if(recipients.length>10||recipients.some(v=>!/^\S+@\S+\.\S+$/.test(v)))throw new Error('Invalid to');stringField(o,'subject',300);stringField(o,'body',20000);return o},execute:i=>({draftId:GmailApp.createDraft(String(i.to),String(i.subject),String(i.body)).getId()})},
 {name:'gmail.sendDraft',description:'Send an existing Gmail draft',risk:'send',validate:i=>{const o=required(i,['draftId']);stringField(o,'draftId',200);return o},execute:i=>{const draft=GmailApp.getDraft(String(i.draftId));if(!draft)throw new Error('Draft not found');draft.send();return{sent:true}}},
 {name:'calendar.list',description:'List calendar events',risk:'read',validate:period,execute:i=>CalendarApp.getDefaultCalendar().getEvents(new Date(String(i.start)),new Date(String(i.end))).map(e=>({id:e.getId(),title:e.getTitle(),start:e.getStartTime().toISOString(),end:e.getEndTime().toISOString()}))},
 {name:'calendar.create',description:'Create calendar event',risk:'write',validate:i=>{const o=period(i);stringField(o,'title',300);optionalString(o,'description',5000);return o},execute:i=>({eventId:CalendarApp.getDefaultCalendar().createEvent(String(i.title),new Date(String(i.start)),new Date(String(i.end)),{description:String(i.description??'')}).getId()})},
 {name:'calendar.update',description:'Update a calendar event',risk:'write',validate:i=>{const o=required(i,['eventId']);stringField(o,'eventId',500);optionalString(o,'title',300);if((o.start===undefined)!==(o.end===undefined))throw new Error('start and end must be provided together');if(o.start!==undefined)period(o);if(o.title===undefined&&o.start===undefined)throw new Error('No calendar changes provided');return o},execute:i=>{const event=CalendarApp.getDefaultCalendar().getEventById(String(i.eventId));if(!event)throw new Error('Event not found');if(i.title)event.setTitle(String(i.title));if(i.start&&i.end)event.setTime(new Date(String(i.start)),new Date(String(i.end)));return{eventId:event.getId(),updated:true}}},
 {name:'drive.search',description:'Search Drive files',risk:'read',validate:i=>{const o=required(i,['name']);stringField(o,'name',300);return o},execute:i=>{const fs=DriveApp.getFilesByName(String(i.name)),out=[];while(fs.hasNext()&&out.length<10){const f=fs.next();out.push({id:f.getId(),name:f.getName(),url:f.getUrl()})}return out}},
 {name:'drive.createFolder',description:'Create a Drive folder',risk:'write',validate:i=>{const o=required(i,['name']);stringField(o,'name',300);return o},execute:i=>{const f=DriveApp.createFolder(String(i.name));return{id:f.getId(),url:f.getUrl()}}},
 {name:'docs.read',description:'Read a Google Doc',risk:'read',validate:i=>{const o=required(i,['documentId']);googleId(o,'documentId');return o},execute:i=>({text:DocumentApp.openById(String(i.documentId)).getBody().getText().slice(0,30000)})},
 {name:'docs.create',description:'Create a Google Doc',risk:'write',validate:i=>{const o=required(i,['title','content']);stringField(o,'title',300);stringField(o,'content',30000);return o},execute:i=>{const d=DocumentApp.create(String(i.title));d.getBody().setText(String(i.content));d.saveAndClose();return{id:d.getId(),url:d.getUrl()}}},
 {name:'sheets.read',description:'Read a range from Google Sheets',risk:'read',validate:i=>{const o=required(i,['spreadsheetId','sheetName','range']);googleId(o,'spreadsheetId');stringField(o,'sheetName',200);stringField(o,'range',100);return o},execute:i=>{const sheet=SpreadsheetApp.openById(String(i.spreadsheetId)).getSheetByName(String(i.sheetName));if(!sheet)throw new Error('Sheet not found');return{values:sheet.getRange(String(i.range)).getValues()}}},
 {name:'sheets.append',description:'Append a row to Google Sheets',risk:'write',validate:i=>{const o=required(i,['spreadsheetId','sheetName','values']);googleId(o,'spreadsheetId');stringField(o,'sheetName',200);if(!Array.isArray(o.values)||o.values.length===0||o.values.length>100)throw new Error('values must contain 1 to 100 cells');if(o.values.some(v=>v!==null&&!['string','number','boolean'].includes(typeof v)))throw new Error('values contain an unsupported cell type');return o},execute:i=>{const sheet=SpreadsheetApp.openById(String(i.spreadsheetId)).getSheetByName(String(i.sheetName));if(!sheet)throw new Error('Sheet not found');sheet.appendRow(i.values as unknown[]);return{appended:true}}},
 {name:'tasks.list',description:'List Google Tasks',risk:'read',validate:i=>{if(i!==undefined&&i!==null&&typeof i!=='object')throw new Error('Input must be an object');return(i??{}) as Record<string,unknown>},execute:()=>Tasks.Tasks?.list('@default')},
 {name:'tasks.create',description:'Create Google Task',risk:'write',validate:i=>{const o=required(i,['title']);stringField(o,'title',500);optionalString(o,'notes',5000);if(o.due!==undefined)dateField(o,'due');return o},execute:i=>Tasks.Tasks?.insert({title:String(i.title),notes:String(i.notes??''),due:i.due?String(i.due):undefined},'@default')},
 {name:'tasks.complete',description:'Mark an existing Google Task completed',risk:'write',validate:i=>{const o=required(i,['taskId']);googleId(o,'taskId');if(o.taskListId!==undefined)googleId(o,'taskListId');return o},execute:i=>Tasks.Tasks?.patch({status:'completed',completed:new Date().toISOString()},String(i.taskListId??'@default'),String(i.taskId))},
 {name:'messaging.notifyOwner',description:'Send a proactive LINE message to the owner',risk:'send',validate:i=>{const o=required(i,['text']);stringField(o,'text',5000);return o},execute:(i,c)=>{notifyOwner(c.message.conversationId,String(i.text));return{sent:true}}}
];

export class ToolRegistry {private enabled:AgentTool[];private map:Map<string,AgentTool>;constructor(workspaceEnabled=false){this.enabled=workspaceEnabled?tools:tools.filter(tool=>tool.name==='messaging.notifyOwner');this.map=new Map(this.enabled.map(tool=>[tool.name,tool]))}get(name:string){return this.map.get(name)}declarations(){return this.enabled.map(t=>({name:t.name,description:t.description,risk:t.risk}))}}
function notifyOwner(to:string,text:string){const token=PropertiesService.getScriptProperties().getProperty('LINE_CHANNEL_ACCESS_TOKEN');if(!token)throw new Error('Missing LINE token');const response=UrlFetchApp.fetch('https://api.line.me/v2/bot/message/push',{method:'post',contentType:'application/json',muteHttpExceptions:true,headers:{Authorization:`Bearer ${token}`},payload:JSON.stringify({to,messages:[{type:'text',text}]})});const code=response.getResponseCode();if(code<200||code>=300)throw new Error(`LINE push failed: ${code}`)}
